name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies #установка настроек
        run: |
          sudo apt update && sudo apt install -y python3-pip 
          pip3 install -r requirements.txt
        #обновление информации о пакетах. устанавливаем пип для питона. уттснавливает все библиотеки из файла requirements

      - name: Run Flask tests #запускаем тест. в случае если тест не проходит, то обновление сайта не произойдёт
        run: |
          python -m pytest tst.py

      - name: Deploy to Server #подключение к серверу используя внутренню функцию подключения к другому серверу
        continue-on-error: true
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/admina/new/cd
            git pull
            pkill -f gunicorn
        
        
      - name: Run on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/admina/new/cd
            gunicorn3 --workers=3 app:app --daemon

